### ISSUE TITLE
Non-Newtonian fluid

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#10]
[Referenced doc]
Fingerprint Toolbox Inventory - C.1　 Non-Newtonian fluid, also known as Dilatant compound

[Questions]
I have the following questions.

Q1. How can you determine the chemical composition? I can’t find any research papers that use dilatant for making the fingerprint PAI and I want to know such specific chemical composition can works for all type of sensors.

Q2-1. Does the evaluator need to follow the chemical composition precisely?

Q2-2. If answer to Q2-1 is yes, are there any commercial product that follow the chemical composition? If yes, the product name should be added to the toolbox inventory as an example.

Q2-3. If answer to Q2-1 is yes but Q2-2 is no, the evaluator needs to purchase all materials listed in C.1. Is it easy enough for inexperienced evaluators to purchase them and create the PAI as specified in C.1?

**Comment by gregott** [comment]
My expectation is that the evaluator will purchase commercially available Dilatant compound as opposed to making his own.  A quick Internet search on "Dilatant compound" will turn up a very familiar commercial product.  It is this product that is used in all Dilatant compound based fingerprint attacks I have seen on the Internet.  

I was instructed by NIAP to not use any brand name products in the toolbox as the US Government cannot endorse, or appear to endorse, any company's product.  Even though I fully believe all the labs will purchase a specific product for all their testing, I was not allowed to name that product.  Instead I had to use generic descriptions such as modeling compound, Non-Newtonian fluid, or an unspecified powdered food grade gelatin with specific Bloom hardness values and so on.

If we assume the labs will use the commercially available product I am thinking of, most of your questions should go away.  I do not know if we are allowed to list the commercial product in the toolbox.  However, it should be noted that the references do name the commonly recognized commercial products.

**Comment by n-kai** [comment]
@gregott 
Thank you for answering my questions. 
If we are not allowed to list the commercial product in the toolbox, we should add a note that explain such dilatant compound is commercially available, at least.

**Comment by woodbe** [comment]
I don't know that we have a prohibition on listing specific products, but I like having descriptions without a "use this one" type of requirement. What may be useful in the case of fingerprint though, since it is different than the other modalities, would be to provide an "examples" column where we could list some commercial products that are used commonly. We could add some text that the examples provided here are for reference, and that the lab can/should investigate what works best for them (since one person may have a preference, I guess). 

I don't see a problem providing examples in addition to the "requirement" of the compound, so you could explicitly state to make modeling compound, and have PLAY-DOH as a commercial example. Ideally we would want more than one (since they are examples), but this way we could provide a guide without getting into any recommendation.

**Comment by woodbe** [comment]
@woodbe will work on this with #2 for example products that can meet the requirements
