### ISSUE TITLE
Attack 2D Fingerprint 01-01 

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#11]
[Referenced section]
Recipe – cast

[Comment]
Recipe – cast in Fingerprint 01-01 is different from Fingerprint 02-01 and 03-01 (e.g. there is no specific chemical composition described)

[Proposed change]
If this is an editorial mistake, correct it. If not, add the specific chemical composition to 01-01 too.

(If #4 (proposes to remove the transparency mold) is accepted, this one can be skipped)

**Comment by woodbe** [comment]
@n-kai I'm doing some reformatting on these (in stages) to move some of the things about the composition and such (like the recipe about making gelatin) to only be in the inventory instead of having it specifically in the attack steps. 

Eventually I think we will be able to combine these into something like 5 tests with variants as we have done with the other modalities, but for now I've been trying to tweak them for this.
