### ISSUE TITLE
Overview: Lossless Images Only

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Fingerprint-Toolbox#31]
The overview states:
> The image file is preferred to be in bitmap, TIFF, RAW or other uncompressed file format when received from the scanner. High quality JPEG files are acceptable if uncompressed formats are not available.

I believe we should require lossless image acquisition from the sensor. Although we binarize the image after acquisition, compression artifacts may alter the resulting 1-bit image, which will make a less-robust mold. I don't see a reason why we should not require use of a sensor's capability to provide a lossless image.

**Comment by woodbe** [comment]
@gfiumara do we know for certain that the scanners will output uncompressed in all cases? I'm OK saying this as long as that is common, but I think the point here was to accept the JPEG only if that is all that can be output. I would agree about lossless, I just don't know enough about the scanners to to say.

**Comment by gfiumara** [comment]
@woodbe While I can't answer with certainty, every scanner I've developed against had the option of returning raw bytes. Most development kits include additional codecs as well. I would guess strongly that if any compressed codec is provided, WSQ compression would be supported, as it is the default for 500 PPI compression in ANSI/NIST-ITL. I don't know of any national systems that allow lossy JPEG compressed images except for in legacy data ingestion only.

**Comment by woodbe** [comment]
I'm good with the change then (as I proposed to just remove the sentence) unless anyone else has a specific comment.

**Comment by gregott** [comment]
If lossless image formats are available from the scanner, then those are the image formats we should require.  However, I would not want to preclude using a scanner that provides acceptable image quality just because it does not have RAW output, especially if it meets all other requirements.  I believe WSQ is lossy.  Actually I think it is better to use the term lossless instead of uncompressed as there are lossless compression techniques.  Perhaps we should say “RAW or lossless compressed image file formats are preferred.  Image file formats with lossy compression are acceptable if lossless formats are not available.”

**Comment by woodbe** [comment]
@gregott will look at output formats to see what the suggested scanners support.

@woodbe will update the text to be more open to lossless formats and allow WSQ compression as a proposed update.
