### ISSUE TITLE
Overview: Don't Allow Interpolation

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Fingerprint-Toolbox#32]
Overview:
> Resizing the image with interpolation should be minimized.

Why would the image need to be resized, introducing interpolation? Suggest we explicitly disallow resizing of the image.

**Comment by woodbe** [comment]
I think this should be OK. I would expect any printer should be able to print to the correct size from the source, and that any "resizing" so to speak should probably happen there instead of in the image processing.

**Comment by n-kai** [comment]
If you create the PAI from a residual fingerprint on glass surface, you have to brash the fingerprint with powder, lift the dusted print and photograph the lifted fingerprint by camera. In this case, you have to resize the fingerprint image taken by the camera. The toolbox capture the fingerprint image directly from a user, so resizing is unnecessary.

**Comment by gregott** [comment]
You can resize a photograph with or without interpolation.  When a fingerprint image is provided by a scanner, the file will be X pixels wide and Y pixels high.  The photo manipulation software does not know what the PPI of the image is, only how many pixels are in the image.  Some photo software assumes a PPI of 72, which is common for screen display.  So when opening a scanner image in this software the image is going to be displayed at 72 PPI.  This will not provide a life-sized image if printed.  The tester must tell the software the correct PPI to use.  If you use the same PPI as stated in the scanner specs you should get a life-sized image.  Assuming the scanner resolution is 1000 PPI, the user must resize the image from 72 PPI to 1000 PPI.  Resizing without interpolation will give you a life-sized image with no loss of quality due to interpolation.  Resizing with interpolation not only introduces artifacts but will also impact the size of the fingerprint when printed.

When working with latent images you will always need to resize with interpolation.  When working with scanners you generally will not need to use interpolation.  One time when you might want to use interpolation is if you have a 500 PPI image and you want to print it at 1000 PPI while a maintain life-sized image.  You could use interpolation to provide smoother edges when scaling up the image.  Depending on your needs, accepting the interpolation artefacts may be permissible in this situation.  Other times you may not be able to accept these artefacts.  In our case interpolation should be avoided when resizing a fingerprint image coming from a scanner.

**Comment by woodbe** [comment]
@woodbe will create a new PR to adjust this to say should not use interpolation for resizing. If this recommendation is not followed, the lab needs to provide a justification.
