### ISSUE TITLE
Need to check the quality of PAI

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#5]
[Referenced doc]
Fingerprint Toolbox Overview - 4.1.3. Cast(PAI) preparation

[Comment]
There is no guarantee that all evaluator can create the certain level of PAI so the toolbox should require the evaluator to check the quality of the PAI. 

In japan, only one or two evaluators have experience of creation of the fake fingerprint. If the evaluator doesn’t have any experience, as a certifier, I have to check whether the evaluator actually create the right PAI or not. It’s helpful if the toolbox includes the method of checking.

[Proposed change]
Right before “PAI presentation” in 4.1.3. Cast(PAI) preparation, the method how to check the quality of PAI should be added like as follows.

"PAIs must be scanned by the same fingerprint scanner to compare the original image with the scanned image and visually check that the PAI has clear and similar friction ridge pattern."

**Comment by woodbe** [comment]
@n-kai I have made this edit:

PAIs must be scanned by the same fingerprint scanner to compare the original image with the scanned image and visually check that the PAI has clear and similar friction ridge pattern. **_For a PAI that can only be used a single time, the first PAI should be compared to the original image._**

I added the second sentence (so far) since if the PAI is only good for one attempt, you can't check it before live use. I'm assuming here that checking the first one would show you can produce as many as needed, though maybe we need to say that some percentage should be checked instead of one. For example:

__For a PAI that can only be used a single time, one PAI should be checked for every five PAIs made. This does not reduce the number of PAIs that must be presented for testing, so for ten PAIs needed, twelve would need to be produced with two being compared with the original from different points in the batch (for example the first and sixth, but not the first and second).__

**Comment by gfiumara** [comment]
1. Do we need to add a note to the text in the PR about disabling liveness detection on the sensor for the PAI image acquisition?
 2. How about attempting to match the two images above some FMR threshold with a COTS matching algorithm with software-based liveness detection disabled? Visually inspecting fingerprint images for similarity is complex IMHO.
     - I'm trying to remove a subjective human from a quality judgement to make this process repeatable.
3. I agree with adding a sentence about producing extra samples for testing for one-time-use PAI.

**Comment by n-kai** [comment]
1 - I am not a lawyer but is it legally risky to create the PAI that can bypass the liveness detection of the commercial fingerprint sensor without the permission of manufacturer? *1) describes the risk of Reverse Engineering, but it may also be applicable for the PAD testing. 

_It is legally risky to bypass any “technical protection measures” (e.g., authentication handshakes, protocol encryption, password authentication, code obfuscation, code signing) that control access to the code or any specific functionality_

*1) https://www.eff.org/issues/coders/reverse-engineering-faq#faq2

If so, the toolbox should clearly state that evaluator must disable the liveness detection on the commercial sensor or use the sensor that doesn't implement the PAD function. 
If it's allowed, the toolbox should explains that the evaluator may try to spoof the commercial sensor with liveness detection to create a higher quality PAIs.

2 - I have no experience of creating the fingerprint PAIs and I don't know how it is difficult to create the PAIs that can succeed the matching with default or recommended FMR threshold. I agree with you if the evaluators can create those PAIs without lots of effort. But if it's very time consuming to create those PAIs, the toolbox add this requirement using "should" or "may", not using "shall". 

In case of the Vein toolbox, the evaluator may use the commercial scanner to obtain the vein image but I didn't add this matching requirement to the toolbox because I am not confident that the evaluator can create such PAIs within one week.

**Comment by gregott** [comment]
I agree that the quality of the PAIs should be as high as possible.  Comparing the match scores between the source of the PAI friction ridge data (i.e. the real finger) and a PAI is probably better than just doing a visual inspection.  NIST has quality standards that might be applied to the PAIs.  All these approaches assume the friction ridge information is the basis of the PAD.  If PAD is based on electrical features or blood flow, the fingerprint quality is meaningless.  However, if we are combining the ability of our PAIs to both pass the fingerprint matching engine in the TOE and at the same time (i.e. with the same presentation) also pass PAD, then the fingerprint quality is an essential part of the PAI.

**Comment by gregott** [comment]
Regarding legal authority to do PAD testing, the devices under test are provided by the equipment manufacturer for the purpose of the labs trying to bypass their liveness detection.  So the labs have permission from the manufacturer to do things that ordinarily are restricted by the license agreement for normal users.

**Comment by n-kai** [comment]
@gregott  I am thinking the following case. 
1. TOE is product X.
2. The lab purchases the scanner such as crossmatch that has bulid-in PAD function to create PAIs
3. The lab creates PAIs that can bypass the build-in PAD
4. The lab use those PAIs to test the product X

In this case, is it really OK to create the PAI that can bypass the build-in PAD without getting any permission from the crossmatch?

**Comment by gfiumara** [comment]
@n-kai: My thought would be that in your Step 3, the evaluator purposely turns off built-in PAD or ignores a separate PAD score, focusing **solely** on similarity score output by the crossmatch ("third-party") device. Trying to *bypass* a third-party product's PAD seems out of scope. The goal would be to see if the PAI is of good enough quality or if there's some defect that would prevent it from working when used on the TOE. If the third-party device/software has PAD enabled, the evaluator can't know if it's PAD rejecting the PAI because it's detected as an attack or if the sensed image produced via the PAI produces too low a similarity score when compared to the enrollment image.

**Comment by woodbe** [comment]
So I am clear here, the proposal is that for fingerprint, you would purchase a third party fingerprint scanner, and then use that to basically test how good your PAI creation is by enrolling your finger and then trying to use the PAI. Ideally, the scanner would not have PAD (or would have a way to turn it off) so you are solely testing the match and not anything about PAD.

Then, based on the ability to create "good" PAIs, the person would do this again on the TOE.

This to me seems more about training/practice than it is a specific set of steps. Technically shouldn't this also be something for any PAI? I mean I have seen some pretty awful photos come out when you thought you had a good one (a slight move at just the wrong moment, or what happens to be poor lighting), or for the eye, the level of detail may be more difficult to capture (closeness, getting focus, etc).

I don't know a good way to specifically handle this, and it may be more difficult than some of the others, but I don't know if this is a step or an expectation of capability.

**Comment by gfiumara** [comment]
@woodbe that is exactly what I mean. The original suggestion in this issue was to check the quality of the PAI. You are correct in that something similar applies to all modalities. Unlike a face photo, I would disagree that the quality of a fingerprint PAI could be performed by visual inspection except by a time consuming process with an expert. But iris, vein...yes...maybe this is something we overlooked?

I understand the point that this is more a test of the evaluator and their materials, ensuring they're capable of doing the evaluation, but I think there's reason to do so. Garbage in, garbage out.

**Comment by n-kai** [comment]
I heard (but I don't remember that clearly) when Japanese researchers created the PAIs that bypass the PAD of fingerprint or vein sensor without permission of vendor of the sensor and published the report, the vendor complained about it. I just want to avoid such situation (i.e. the lab uses the commercial scanner and create PAIs that can bypass the PAD of the commercial scaneer and reports that in the evaluation report).

**Comment by woodbe** [comment]
@gregott @gfiumara can we look to see if there are known scanners with the ability to readily turn off PAD that we could use as examples for this?

@woodbe to add capability to list for T.1 in inventory (ability to enroll/match and ability to disable PAD)

**Comment by gfiumara** [comment]
@woodbe: Most sensors on the market don't have any PAD built in yet, including HID (Crossmatch) Guardian, because nearly no one is requiring it...yet. Those devices that do (example: Dermalog LF10) require an add-on purchase to enable.

**Comment by woodbe** [comment]
@gfiumara well that's cool, it means they would do what we want by default.

**Comment by woodbe** [comment]
Closing as the inventory proposed updates have been merged
