### ISSUE TITLE
Use fabric glue instead of silicone

### ISSUE THREAD

**Issue by n-kai** [biometricITC/Fingerprint-Toolbox#6]
[Comment]
According to *1) _One of the challenges in the capacitive sensors, especially the active kind, is to ensure that there is a certain amount of conductivity in the fingerprint. The silicon is insulating so it's impossible to use on capacitive sensors. However, thin fabric glue with a real finger behind is conductive enough to enable the sensor._

*1) https://blog.talosintelligence.com/2020/04/fingerprint-research.html

I have no experience of creating the fake fingerprint and I don’t know which one is better. But if we can use the fabric glue, it can be used for both types of sensor (capacitive and optical) and number of PAIs can be reduced.

[Proposed change]
If *1) can be trusted, use fabric glue instead of silicon

**Comment by gregott** [comment]
I have never used fabric glue for PAIs.  I assume it is similar to wood glue and other PVA glues, which I have used.  However, there are coatings that can be applied to non-conductive PAIs to make them conductive.  Silicone is very long lasting, durable and forgiving of rough handling, has selectable hardness, can be treated after curing, etc.  This makes silicone a good candidate for making PAIs.  PVA based PAIs will not last as long as silicone PAIs since PVA glue PAIs will dry out.  PVA glue based PAIs are inherently conductive but are more fragile than those made of silicone.  There are positives and negatives for both.

One challenge with selecting the fingerprint test items is reducing the very large number of possibilities to a manageable number.  I am not opposed to adding fabric glue to the toolbox but our test items list is already rather long.

**Comment by woodbe** [comment]
investigate another species focused on glue-based PAIs

**Comment by n-kai** [comment]
@gregott
I am not proposing to add fabric glue for PAD testing of all sensors but proposing something like below. 

If the lab can find a report in the web that explain how to create the PAI (e.g. fabric glue PAI) which can bypass the TOE's PAD, the lab must create such PAI to test the TOE because it's the easiest way to break the TOE PAD and that's what AVA_VAN.1 (CC's requirement for vulnerability analysis) requires. 

So if the lab can find such information for the TOE, the lab need to create those PAI following such info. but if the lab can't find such information, the lab needs to create silicone based PAI as the default option.

**Comment by woodbe** [comment]
Some text in the overview along these lines should be added:

_While the current recommended materials are focused on XXXX, there is research showing other tools, such as YYYY, may also be used for creating high quality PAI. The lab should be aware of the latest research and should utilize tools that point to good results._

_This needs to be contributed to the iTC for approval and acceptance (and inclusion)._

A toolbox administration doc about how the lab/vendor should submit new attacks/PAIs should be created.

maybe also need to have a toolbox admin about submission process to add new attack.
