### ISSUE TITLE
CSM 11: Add mention of skin conditions to testing protocol

### ISSUE THREAD

**Issue by woodbe** [biometricITC/Fingerprint-Toolbox#65]
https://github.com/biometricITC/Fingerprint-Toolbox/blame/06896fdb6efabdb959c6e3190af76c2b9255057a/FINGERPRINT_Toolbox_Overview.adoc#L90

CSM 11: To add in checking quality of finger in use in order to have high quality samples. 

Proposal: Certain fingers unable to produce good impression due skin conditions. 

From spreadsheet

**Comment by n-kai** [comment]
This is common issue to all biometric verification. That's why "5.1.1. Preparation" in  "Biometric PAD Toolbox Overview" (see below) instructs the evaluator to enrol a test subject at least 5 times (normally quality check during enrollment is stricter than one during verification). If  skin condition of test subject's finger is not good, he/she can't be enrolled 5 time in succession.
 
_At least 5 test enrolment transactions shall be performed by the test subject to ensure that the test subject can enrol correctly and be verified after enrolment._

**Comment by woodbe** [comment]
So I can say we can close this for that point, but as a thought, should we make a mention of it here? Something like saying (at the end of the intro paragraph) to check the Toolbox overview?

I can see why they are thinking this, as they assuredly read it in isolation. I do not know how many other people will do the same, so I'm wondering if we should add a reference back to the main overview document here as a reminder.

**Comment by gregott** [comment]
If it caused one of us to wonder about it, I am sure those not involved in authoring the document will have the same reaction.  I am fine with including a reference.

**Comment by n-kai** [comment]
I also agree to add a reference
