### ISSUE TITLE
Moldable Plastics Instructions/Recipe

### ISSUE THREAD

**Issue by DouglasKalmus** [biometricITC/Fingerprint-Toolbox#77]
Instructions are not given for M.4 Moldable Plastic in the Toolbox Inventory. Additionally, many of the materials do not list a commercial example, which will be beneficial for labs to have when choosing equipment. Proposing that instructions be provided for the mold type and commercial example(s) given for all required equipment.

**Comment by woodbe** [comment]
For the materials that do not have listed commercial examples, it is largely because there were not specific "set" recommended examples that were clear to be used. If there are specific suggestions they can be added, but the iTC at the time this was written was not certain of any particular recommendations that should be made for those materials.
